version: "3.4"

networks:
  monitoring:
    driver: overlay

services:

  api:
    image: cache-server:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/:/etc/prometheus/
      - ./infra/prometheus/data:/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/proc"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor:latest
    deploy:
      mode: global
    restart: unless-stopped
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
    expose:
      - 8080
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./infra/grafana/data:/var/lib/grafana
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
      - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=false
      # - GF_SMTP_HOST=smtp.gmail.com:587
      # - GF_SMTP_USER=myadrress@gmail.com
      # - GF_SMTP_PASSWORD=mypassword
      # - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    networks:
      - monitoring
